// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV6nKhDM5RYrG7MRvEfr_CjiEnFsDK3lQ',
    appId: '1:553350879520:web:acd444e708d57445e89f45',
    messagingSenderId: '553350879520',
    projectId: 'chatwithme-1545f',
    authDomain: 'chatwithme-1545f.firebaseapp.com',
    storageBucket: 'chatwithme-1545f.appspot.com',
    measurementId: 'G-FM8QL0SQWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdvLNNGl9EtXaK9jWAFvWMd3uBDzkV3EY',
    appId: '1:553350879520:android:6a3b835a3141bd2de89f45',
    messagingSenderId: '553350879520',
    projectId: 'chatwithme-1545f',
    storageBucket: 'chatwithme-1545f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9tNMnvGddM6PVZfPRRWDGcC3ZX4KNc7g',
    appId: '1:553350879520:ios:a8dece8975bf6391e89f45',
    messagingSenderId: '553350879520',
    projectId: 'chatwithme-1545f',
    storageBucket: 'chatwithme-1545f.appspot.com',
    iosClientId: '553350879520-932a67582m4djj2hvdaj36o62iv0tt9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9tNMnvGddM6PVZfPRRWDGcC3ZX4KNc7g',
    appId: '1:553350879520:ios:a8dece8975bf6391e89f45',
    messagingSenderId: '553350879520',
    projectId: 'chatwithme-1545f',
    storageBucket: 'chatwithme-1545f.appspot.com',
    iosClientId: '553350879520-932a67582m4djj2hvdaj36o62iv0tt9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
